/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGuardRouteImport } from './routes/_authenticated/guard'
import { Route as AuthenticatedResidentRouteImport } from './routes/_authenticated/resident'
import { Route as CTokenRouteImport } from './routes/c.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGuardRoute = AuthenticatedGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResidentRoute = AuthenticatedResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guard': typeof AuthenticatedGuardRoute
  '/resident': typeof AuthenticatedResidentRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guard': typeof AuthenticatedGuardRoute
  '/resident': typeof AuthenticatedResidentRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/guard': typeof AuthenticatedGuardRoute
  '/_authenticated/resident': typeof AuthenticatedResidentRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/guard' | '/resident' | '/c/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/guard' | '/resident' | '/c/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/guard'
    | '/_authenticated/resident'
    | '/c/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guard': {
      id: '/_authenticated/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof AuthenticatedGuardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resident': {
      id: '/_authenticated/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof AuthenticatedResidentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGuardRoute: typeof AuthenticatedGuardRoute
  AuthenticatedResidentRoute: typeof AuthenticatedResidentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGuardRoute: AuthenticatedGuardRoute,
  AuthenticatedResidentRoute: AuthenticatedResidentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
